plugins {
    id 'java-library'
    id 'com.vanniktech.maven.publish' version '0.34.0'
}

apply plugin: 'signing'
signing {
    useGpgCmd()
    sign publishing.publications
}


group = 'io.github.isthisalis'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

mavenPublishing {
    publishToMavenCentral()

    coordinates('io.github.isthisalis', 'ailib', '1.0.0')

    pom {
        name = 'AiLib'
        description = 'Library for interactions with AI'
        url = 'https://github.com/IsThisALis/AiLib'

        licenses {
            license {
                name = 'MIT'
                url = 'https://opensource.org/licenses/MIT'
            }
        }

        developers {
            developer {
                id = 'IsThisALis'
                email = 'gamemodebronze2@gmail.com'
            }
        }

        scm {
            url = 'https://github.com/IsThisALis/AiLib'
        }
    }
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'tools.jackson.core:jackson-databind:3.2.0'
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.2.0'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
}

tasks.named('test') {
    useJUnitPlatform()
}

afterEvaluate {
    tasks.configureEach { task ->
        if (task.name.contains('generateMetadataFile')) {
            task.dependsOn tasks.matching { it.name.contains('JavadocJar') }
        }
    }
}
